// Generated by https://quicktype.io

export interface IPokemonResponse {
	count: number;
	next: string;
	previous: null;
	results: ISmallPokemon[];
}

export interface ISmallPokemon {
	name: string;
	url: string;
}

export interface IPokemon {
	id: string;
	name: string;
	imgURL: string;
}
